### ISSUE TITLE
HBase remotely connecting to python project

### ISSUE THREAD

**Issue by haonly-kim** [python-happybase/happybase#239]
Hi I am currently working on my first project with hbase.
I've got a remote instance and trying to connect.

### Connection
I've successfully connected like below

```python
connection = happybase.Connection(host=host, port=port, protocol='compact',transport='framed')
table = connection.table('table_name')
```

### Error
I want to put data to the table with this code:
```python
table.put(b'id1-123', {b'played:trackIds': trackIds,
                       b'played:dt': dt})
```
 and it returned me the error below.
```
TTransportException: TTransportException(type=4, message='TSocket read 0 bytes')
```

### Configures
I figured it out that I need to configure below properties
```
zookeeper.znode.parent
hbase.zookeeper.property.clientPort
hbase.zookeeper.quorum
```

I am wondering how am I supposed to set those properties on my python project?

I've found some solutions for Java users but I cannot find it for python user 😭 

I would be really really appreciated if anyone helps me!

**Comment by wbolster** [comment]
i think you are not actually connecting to the thrift service which happybase depends on.

**Comment by Haonly** [comment]
Hi thank you for leaving comment! 

So do you mean that I need to connect to the thrift as well as Happybase?

**Comment by wbolster** [comment]
ehm, did you read the docs? happybase is a client so you cannot connect to it. happybase connects to hbase thrift.

**Comment by haonly-kim** [comment]
Um, I did and I thought I could put data to hbase table with Happybase and it seems like I need to configure something.

**Comment by wbolster** [comment]
you need to run the thrift service on the hbase side, and then you can use happybase to connect to it.

**Comment by haonly-kim** [comment]
Hi!
I run the thrift service on the hbase side and it works very well! 
I thought I run the thrift but I was not.

Thanks for helping me out.

**Comment by wbolster** [comment]
cool! thanks for letting me know 😃
