### ISSUE TITLE
How can I do a query for specific columns by regex-statement

### ISSUE THREAD

**Issue by johnny4173** [python-happybase/happybase#246]
Hi,

I have several columns by the schema family:qualifier. Here are the columns with the values for the first row:
```
b'data:name':` b'test33',  
b'data:appender.0.more.deep.0.name': b'nested', 
b'data:appender.0.more.deep.0.value': b'4711', 
b'data:appender.0.more.deep.1.name': b'nested2', 
b'data:appender.0.more.deep.1.value': b'42', 
b'data:appender.0.more.name': b'Alex', 
b'data:appender.0.more.process': b'buy', 
b'data:appender.0.more.value': b'1.0', 
b'data:appender.0.id': b'32542352352354432', 
b'data:appender.1.more.name': b'Andrew', 
b'data:appender.1.more.process': b'sell', 
b'data:appender.1.more.value': b'20.0', 
b'data:appender.1.id': b'deaf3232432', 
…
b'data:appender.47110.more.deep.name': b'3rfsdf3', 
b'data:appender.47110.more.deep.value': b'412', 
b'data:appender.47110.more.name': b'Jenny', 
b'data:appender.47110.more.process': b'buy', 
b'data:appender.47110.more.value': b'10.0', 
b'data:date': b'2020-11-02 12:18:49.479229', 
b'data:ob.0.cd': b'902359874598459834985093', 
b'data:ob.0.n': b'235a3ff4234234',    
b'data:s.c': b'hco', 
b'data:s.s.p': b'nm',  
b'data:id': b'5345345'
```

The question is how can I query the row with happybase where at least one column 'data:appender._NumberX_.more.deep._NumberY_.value' has for example the value 42. The maximum number of _NumberX_ or _NumberY_ is not known to me and can be different in each row. _NumberY_ need not necessarily exist in each row as you can see in the example above. The same applies to _NumberX_.

I don't know how do I query this with python/happybase for columns because I am new to HBase/happybase. First I would to detect the numbers for the columnnames like this re.findall(".[0-9]*.", key) and then replace it with a dot. I want to create a query like this data:appender.more.deep.name that looks in all possible columns (e.g. in 'data:appender.47110.more.deep.value' or 'data:appender.0.more.deep.0.value' or 'data:appender.0.more.deep.1.value'.

How is this in python/happybase possible to do this query?

Best thanks in advance.

**Comment by wbolster** [comment]
i think you're looking for the filter=... argument for a scanner.

that filter language is hbase specific (it's just a string in python), and happybase doesn't have anything for that itself. there's some documentation for it, i believe, but it's not in scope for happybase, so perhaps you should ask on a hbase mailing list/forum.

**Comment by wbolster** [comment]
https://www.programmersought.com/article/7766232136/

may provide some pointers and inspiration
