### ISSUE TITLE
import happybase error

### ISSUE THREAD

**Issue by monkeyshichi** [python-happybase/happybase#250]
after install happybase successfully,
import happybase
ImportError: /root/anaconda3/envs/alan_cjf/lib/python3.7/site-packages/thriftpy2/protocol/cybin.cpython-37m-x86_64-linux-gnu.so: undefined symbol: bswap_64

**Comment by wbolster** [comment]
this is not a problem in this repo, but in `thriftpy2`, as you can see in your error.
